// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlpakrakaoyhohjppxkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhscGFrcmFrYW95aG9oanBweGtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNzU3MDYsImV4cCI6MjA2MDY1MTcwNn0.7FKKhpO1mJp5m-UnpjX1pLQPwEQImfDFSSZFORGR0kE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);